resource:
  mysql:
    host: 192.168.1.108
    port: 3306
  redis:
    host: 192.168.1.108
    port: 6379
  influxdb:
    host: 192.168.1.108
    port: 8086

# zk
takin:
  pradar:
    zk:
      server: 192.168.1.131:2181


# mybatis plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

data:
  path: /Users/liyuanba/Downloads
pressure:
  engine:
    install:
      dir: /Users/liyuanba/develop/buildImages/pressure-engine/pressure-engine.tar.gz